apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foodtrack-prod

resources:
  - ../../base
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: foodtrack
      foodtrack.example/env: prod