name: CI/CD FoodTrack

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail -x {0}

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  lint:
    name: Lint des manifestes et du Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.4

      - name: Validation des fichiers Terraform
        run: |
          cd labs/projet-final/terraform
          terraform fmt -check -recursive
          terraform init -backend=false
          terraform validate

      - name: Conformité des manifestes k8s avec Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: -summary -output json k8s/base/*.yaml k8s/overlays/*/*.yaml

  trivy-config:
    name: Scan Trivy des configurations
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4
      - name: Scan Terraform et Kubernetes
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: config
          scan-ref: labs/projet-final
          format: table
          severity: HIGH,CRITICAL
          exit-code: "0"
          hide-progress: true

  trivy-images:
    name: Scan de l'image ${{ matrix.image }}
    runs-on: ubuntu-latest
    needs: trivy-config
    permissions:
      contents: read
    strategy:
      matrix:
        image:
          - nginx:1.30.5
          - us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
          - redis:8.10.1

    steps:
      - name: Scan de l'image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: image
          image-ref: ${{ matrix.image }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: "0"
          hide-progress: true
